"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "../components/section/Navbar";
import Image from "next/image";
import Footbar from "@/components/section/Footbar";
import { useState } from "react";
import { createContext } from "react";
import ProductID from "./[id]/page";

const inter = Inter({ subsets: ["latin"] });
interface UserContextType {
  rizi: string;
  cartFunction: (a: string) => void;
  cart: string
}
export const UserContext = createContext<UserContextType>({ rizi: "", cartFunction: () => {} ,cart:"" });


const rizi ="rizwambkbn"

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// =====================================

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const [cart, setCart] = useState<any>(0);
  const cartFunction=(a:any)=>{
    setCart(a)
  }


  return (
    <html lang="en">
      <body className={inter.className}>

        <UserContext.Provider value={{rizi:rizi,cartFunction:cartFunction,cart:cart}}>
        <Navbar />
        {children}
        <Footbar />
        </UserContext.Provider> 

      </body>
    </html>
  );
}
